before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    dir: .
    main: ./cmd/main.go
    binary: GO-TASK-MGR
archives:
  - id: GO-TASK-MGR
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      - "pacholoamit/go-task-mgr:{{ .Tag }}"
      - "pacholoamit/go-task-mgr:latest"
      - "ghcr.io/pacholoamit/go-task-mgr:{{ .Tag }}"
      - "ghcr.io/pacholoamit/go-task-mgr:latest"

release:
  github:
    owner: pacholoamit
    name: GO-TASK-MGR
  prerelease: auto
  draft: false
  mode: append
  name_template: "{{.ProjectName}}-{{.Version}}"
  header: |
    ## GO TASK MGR Release: {{ .Tag }}! 

    Welcome to this new release!

  # Footer template for the release body.
  # Defaults to empty.
  footer: |
    ## Thanks!

    Those were the changes on ({{ .Date }}) Published by Pacholo Amit
