version: "3.0"

services:
  api:
    container_name: GO-TASK-MGR-API
    image: ghcr.io/pacholoamit/go-task-mgr-api:latest
    ports: 
    - 8081:8081

  client:
    container_name: GO-TASK-MGR-CLIENT
    image: ghcr.io/pacholoamit/go-task-mgr-client:latest
    ports:
    - 3000:3000
