version: "3.0"

services:
  api:
    container_name: GO-TASK-MGR-API
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports: 
    - 8081:8081

  client:
    container_name: GO-TASK-MGR-CLIENT
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
    - 3000:3000
