version: "3.0"

services:
  task-mgr:
    container_name: GO-TASK-MGR
    image: ghcr.io/pacholoamit/go-task-mgr:master
    environment:
      PORT: 8081 # Optional: Default is 8081, sets the server port of the container.
    volumes:
      - ./db:/app/db
    ports:
      - 8081:8081
