# name: docker-ci

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - "master"

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: go-task-mgr

# jobs:
#   push_to_registries:
#     name: Push Docker image to multiple registries
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: true
#       matrix:
#         include:
#           - dockerfile: ./Dockerfile
#             image: ghcr.io/pacholoamit/go-task-mgr
#             context: .
#           - dockerfile: ./Dockerfile
#             image: pacholoamit/go-task-mgr
#             context: .

#     permissions:
#       packages: write
#       contents: read
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Login to Github Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.GHCR_TOKEN }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@v4
#         with:
#           flavor: |
#             latest=true
#           images: ${{ matrix.image }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           context: ${{ matrix.context }}
#           file: ${{ matrix.dockerfile }}
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
